"""Illustrated, bilingual first-person production notes supplied by the creator."""
from html import escape as e
PATH='/notes/fall-707-beginnings/'
ART='/assets/notes/fall-707-season1.png'
TITLE=('습작에서 다시 시작한, 낙하 707 시즌 1','From early experiments to FALL 707 Season 1')
INTRO=('좋아해서 시작했고, 그만둘까 고민했고, 기다려 준 사람들 덕분에 다시 만들었습니다. 낙하 707의 첫 번째 제작 비하인드입니다.','It began with something I loved. I nearly stopped. Then the people waiting for the next episode gave me a reason to start again. This is the first FALL 707 production note.')
NOTICE=('창작자의 경험을 바탕으로 재구성한 일러스트입니다. 실제 제작 화면이나 댓글 캡처가 아닙니다.','Illustrations reconstruct the creator’s experience. They are not archival screenshots or captures of actual comments.')
PANELS=[
(('그냥, 밀리터리가 좋아서.','It started with a love of military films.'),('오늘은 낙하 707이 어떻게 시작됐는지 이야기해 보려고 합니다. 처음부터 거대한 세계관을 계획한 건 아니었습니다. 밀리터리를 좋아해서, 짧은 영상을 한번 만들어 보고 싶었습니다.','Today, I want to share how FALL 707 began. I did not start with a grand universe in mind. I simply loved military films and wanted to try making a short one.'),('안녕하세요, 드래곤시네마입니다!','Hello, this is DRA9ON CINEMA!'),('편집 책상 앞에서 첫 영상을 구상하는 창작자','A creator imagining a first film at an editing desk')),
(('그런데… 조선에 떨어진다면?','But… what if they landed in Joseon?'),('만들다 보니 상상이 이어졌습니다. 현대 특수부대원이 조선시대로 타임슬립하고, 조선의 군인들과 맞서 싸우며 탈출한다면 어떨까? 그렇게 약 2분짜리 첫 영상이 나왔습니다.','One idea led to another: what if a modern special forces soldier travelled back to Joseon, fought its soldiers and tried to escape? That became the first film, about two minutes long.'),('현대의 전술 × 낯선 시대','Modern tactics. An unfamiliar era.'),('조선의 궁궐로 들어서는 현대 특수부대원','A modern special forces soldier entering a Joseon palace')),
(('응원과 악플 사이, 습작 4편.','Four early experiments, between encouragement and harsh comments.'),('이야기가 좋다는 응원도, 날카로운 지적과 악플도 있었습니다. 응원에 힘을 얻어 1~2분 분량의 습작을 4화까지 이어갔습니다. 지금의 정식 시즌 1이 만들어지기 전 이야기입니다.','Some people liked the story. Others left pointed criticism or harsh comments. Encouragement kept me going through four early episodes, each around one to two minutes. These were experiments made before the official Season 1.'),('한 편만 더.','One more episode.'),('네 편의 편집 타임라인과 서로 다른 반응을 그린 장면','Four editing timelines and contrasting audience reactions')),
(('솔직히, 그만둘까 했습니다.','Honestly, I nearly stopped.'),('계속 만들수록 부족함이 보였습니다. 고증을 충분히 챙기지 못한 채 이어가는 건 안 되겠다고 느꼈습니다. 악플까지 겹치면서 낙하 707을 아예 포기할까 고민했습니다.','The more I made, the more I saw what was missing. I could not keep going without addressing the lack of historical research. Together with the harsh comments, it made me consider giving up FALL 707 altogether.'),('여기서 멈출까?','Should I stop here?'),('어두운 작업실에서 제작을 멈출지 고민하는 창작자','A creator in a dark studio considering whether to stop')),
(('다시 시작하게 만든 한마디.','The words that brought me back.'),('그런데 몇 번, 이런 이야기를 들었습니다. 제가 포기할까 고민하던 작품을 누군가는 기다리고 있었습니다. 그 말들이 다시 만들어 볼 힘이 됐습니다.','Then I heard this more than once. Someone was waiting for the story I was thinking of abandoning. Those words gave me the energy to try again.'),('낙하 707 괜찮던데, 더 이상 안 만드나요?','I liked FALL 707. Are you making any more?'),('응원의 반응을 발견하고 다시 빛이 들어오는 작업실','Encouragement bringing light back into the studio')),
(('다음 화 대신, 처음부터 다시.','Instead of the next episode, a new beginning.'),('캐릭터 시트부터 다시 만들었습니다. 세계관과 스토리도 전면적으로 재구성했습니다. 습작을 그대로 이어가는 대신, 처음부터 다시 시작한 것입니다. 그렇게 밀리터리 판타지 오컬트 스릴러, 〈낙하 707: 리부트〉의 정식 시즌 1이 탄생했습니다. 짧은 영상으로 시작한 이야기가, 이제는 계속 이어가고 싶은 저만의 세계가 됐습니다.','I rebuilt the character sheets and reworked the world and story from the ground up. Rather than simply continuing those early experiments, I started over. That rebuild became the official Season 1 of FALL 707: REBOOT, a military fantasy occult thriller. What began as a short video had become a world of my own that I wanted to keep exploring.'),('FALL 707: REBOOT','FALL 707: REBOOT'),('캐릭터 시트와 세계관을 새롭게 구성하는 작업실','A studio rebuilding character sheets and a fictional world')),
]
ASIDES=[('당시의 계획: 짧게. 아주 짧게.','The plan: keep it short. Very short.'),('…배경만 바꾸는 일이 아니었습니다.','…It was not just a change of scenery.'),('분명 하나만 만들 생각이었는데, 어느새 4화.','I meant to make just one. Somehow, there were four.'),('잠깐, 이대로 계속 가도 되는 건가?','Wait. Can I really keep going like this?'),('그 한마디에… 다시 작업실로.','Those words… sent me back to the desk.'),('짧게 만들려던 사람의 다음 계획: 세계관 다시 만들기.','Next on the short-film to-do list: rebuild an entire world.') ]
EXTRA=[('제작 비하인드','Behind the Scenes'),('제작 비하인드 읽기','Read the production note'),('낙하 707: 리부트 1화 보기','Watch FALL 707: REBOOT from episode one'),('DRA9ON CINEMA의 첫 번째 제작 비하인드. 짧은 밀리터리 영상에서 낙하 707: 리부트가 탄생하기까지.','The first DRA9ON CINEMA production note: from a short military video to FALL 707: REBOOT.')]
TRANSLATIONS=dict([TITLE,INTRO,NOTICE,*EXTRA,*ASIDES,*[pair for panel in PANELS for pair in panel]])
TRANSLATIONS[TITLE[0]+' | DRA9ON CINEMA']=TITLE[1]+' | DRA9ON CINEMA'
S2_TITLE=('시즌 2, 민 대위는 왜 달라졌을까?','Season 2: why did Captain Min change?')
S2_INTRO=('검은 군복과 포니테일의 민 대위에서, 더 냉정하고 카리스마 있는 특수부대 대위로. AI 영상 속 캐릭터를 바꾼 이유를 이야기합니다.','From the captain in a black uniform and ponytail to a colder, more commanding special forces officer. Here is why I changed the character in the AI films.')
S2_PANELS=[
(('같은 민 대위, 다른 느낌.','The same captain, a different presence.'),('이번에는 시즌 2의 민 대위가 왜 달라졌는지 이야기해 보겠습니다. 시즌 1의 민 대위는 검은 군복에 포니테일 머리였습니다. 인간적인 면이 드러나는 인물이기도 했습니다. 시즌 2에서는 그때와는 다른 느낌의 민 대위를 보여주고 싶었습니다.','This time, let me share why Captain Min changed in Season 2. In Season 1, Captain Min wore a black uniform and a ponytail. Her human side was visible, too. For Season 2, I wanted her presence to feel different.'),('드래곤시네마, 다시 찾아왔습니다!','DRA9ON CINEMA is back!'),('시즌 1과 시즌 2의 캐릭터 디자인을 비교하는 제작자','The creator comparing the Season 1 and Season 2 character designs')),
(('찾지 못한 대원들. 지나간 3개월.','A missing squad. Three months gone.'),('3개월 동안 대원들을 찾지 못했고, 그 과정에서 방해도 많았습니다. 그런 시간을 보낸 민 대위라면 어떤 표정을 짓고, 어떤 태도로 움직일까? 시즌 2의 변화는 그 생각에서 출발했습니다.','Three months had passed without finding her squad, with obstacles along the way. After that experience, what expression would she wear? How would she carry herself? That question was the starting point for Season 2.'),('3개월이 지났는데, 아직도.','Three months. Still searching.'),('조선의 안개 속에서 대원들을 찾는 민 대위','Captain Min searching for her squad in the mist of Joseon')),
(('더 냉정하게. 더 카리스마 있게.','Colder. More commanding.'),('시즌 2에서는 냉정하고 카리스마 있는 특수부대 대위였으면 했습니다. 외형만 달라지는 게 아니라, 그동안 겪은 시간이 인물의 분위기에서도 느껴지길 바랐습니다.','For Season 2, I wanted a cold, charismatic special forces captain. I wanted the time she had endured to be felt in her presence, rather than just changing her appearance.'),('이번 민 대위는, 눈빛부터.','This time, it starts with the eyes.'),('AI 캐릭터 이미지를 비교하며 눈빛과 분위기를 살피는 제작자','The creator reviewing expressions and presence in AI character images')),
(('조선에… 오토바이요?','A motorcycle… in Joseon?'),('네, 오토바이도 넣었습니다. 이번에는 고증보다 제가 보여주고 싶은 민 대위의 모습과 판타지 연출을 우선한 선택이었습니다. 낙하 707이 밀리터리 판타지 오컬트 스릴러라는 점 안에서, 제가 원하는 장면을 만들어 보고 싶었습니다.','Yes, I included a motorcycle. This was a deliberate choice to prioritize the version of Captain Min I wanted to show and the fantasy staging over historical accuracy. Within a military fantasy occult thriller, I wanted to explore the scene I imagined.'),('네. 이번에는 알고 넣었습니다.','Yes. This time, it was intentional.'),('조선의 거리에서 오토바이를 타는 상처 없는 민 대위','An uninjured Captain Min riding a motorcycle through a Joseon street')),
(('상처에도 순서가 있습니다.','Even a wound has a timeline.'),('얼굴의 상처는 시즌 2의 3화부터 생깁니다. 시즌 1이나 시즌 2 초반부터 있던 상처는 아닙니다. 냉정해진 인물의 분위기와 이후에 생긴 얼굴의 상처는 구분해서 봐주시면 좋겠습니다.','The facial injury begins in Season 2, Episode 3. It was not present in Season 1 or at the start of Season 2. Her colder presence and the facial injury that appears later are separate parts of the character’s progression.'),('상처는 시즌 2, 3화부터!','The wound starts in S2, Episode 3!'),('시즌 2 3화 이후 얼굴에 상처가 생긴 민 대위','Captain Min with a facial injury from Season 2 Episode 3 onward')),
(('AI로 만드는, 저만의 이야기.','A story of my own, made with AI.'),('짧은 밀리터리 영상을 만들어 보자는 마음에서 시작했습니다. 이제는 민 대위가 어떤 시간을 보내고, 어떻게 달라지는지를 생각하며 이야기를 이어갑니다. 낙하 707이라는 저만의 세계를 조금씩 쌓아가고 싶습니다.','I began by wanting to make a short military video. Now I continue by thinking about what Captain Min experiences and how it changes her. I want to keep building my own world through FALL 707.'),('다음 이야기도, 계속 만들어 갑니다.','On to the next part of the story.'),('AI 영상 편집을 이어가는 검은 후드 제작자 캐릭터','The black-hooded creator continuing to edit AI films')),
]
S2_ASIDES=[('캐릭터도, 분위기도 시즌에 맞게.','A design and a mood for each season.'),('찾는 사람은 없고, 방해는 많고.','No squad in sight. Plenty of obstacles.'),('같은 사람이어도, 같은 표정일 수는 없으니까.','The same person does not always wear the same expression.'),('제작자의 판타지 버튼: ON.','Creator’s fantasy switch: ON.'),('제작자 메모: 상처를 미리 그리지 말 것.','Creator’s note: do not add the wound too early.'),('짧은 영상으로 시작했는데, 여기까지 왔네요.','A short video brought us all the way here.')]
S1_CHARACTER=('시즌 1의 민 대위는 검은 군복과 포니테일, 인간적인 면이 드러나는 모습으로 구성했습니다. 이 후기의 얼굴에는 이후 시즌에 생기는 상처를 넣지 않았습니다.','Season 1 presented Captain Min in a black uniform and ponytail, with her human side visible. The later facial injury is not included in this afterword’s Season 1 illustrations.')
NOTES=[{'path':PATH,'season':1,'art':ART,'title':TITLE,'intro':INTRO,'panels':PANELS,'asides':ASIDES,'extra':S1_CHARACTER}, {'path':'/notes/fall-707-season-2/','season':2,'art':'/assets/notes/fall-707-season2.png','title':S2_TITLE,'intro':S2_INTRO,'panels':S2_PANELS,'asides':S2_ASIDES}]
ROUTES=['/notes/']+[n['path'] for n in NOTES]
INDEX_TITLE=('만드는 사람의 이야기','Stories from the creator')
INDEX_INTRO=('AI 영상 뒤에 있는 고민과 선택들. 검은 후드 제작자와 함께 읽는 낙하 707의 시즌별 제작 후기입니다.','The choices and doubts behind the AI films. Read the FALL 707 season afterwords with the black-hooded creator.')
LABELS=[('시즌 1 제작 후기','Season 1 afterword'),('시즌 2 제작 후기','Season 2 afterword'),('후기 목록','Afterword list'),('이전 후기','Previous afterword'),('다음 후기','Next afterword'),('이 시즌 감상하기','Watch this season'),('그림으로 읽는 제작 후기','An illustrated production diary')]
TRANSLATIONS.update([S2_TITLE,S2_INTRO,S1_CHARACTER,INDEX_TITLE,INDEX_INTRO,*LABELS,*S2_ASIDES,*[pair for panel in S2_PANELS for pair in panel]])
for title in [S2_TITLE,INDEX_TITLE]:TRANSLATIONS[title[0]+' | DRA9ON CINEMA']=title[1]+' | DRA9ON CINEMA'
def artwork(note,i,alt):
 return f'<div class="note-art note-art-{i}" role="img" aria-label="{e(alt)}"><img src="{note["art"]}" alt="" width="1374" height="1145" loading="lazy"></div>'
def tiles():
 return '<div class="note-tiles">'+''.join(f'<a class="note-tile" href="{n["path"]}">{artwork(n,1,n["panels"][1][3][0])}<div><p class="section-eyebrow">{LABELS[n["season"]-1][0]}</p><h3>{e(n["title"][0])}</h3><span>{EXTRA[1][0]} →</span></div></a>' for n in NOTES)+'</div>'
def teaser():
 return f'<section class="notes-library" id="production-notes"><p class="section-eyebrow">PRODUCTION NOTES</p><h2>{INDEX_TITLE[0]}</h2><p>{INDEX_INTRO[0]}</p>{tiles()}</section>'
def build_notes(out,origin,head,header,footer):
 for note in NOTES:
  season=note['season'];title=note['title'];intro=note['intro']
  body=f'<body class="watch-page"><div>{header()}</div><main class="production-note" id="main"><header class="note-intro"><a class="note-back" href="/notes/">← {LABELS[2][0]}</a><p class="section-eyebrow">AI FILMMAKING · SEASON {season} · AFTERWORD</p><h1>{e(title[0])}</h1><p>{e(intro[0])}</p><p class="note-credit">DRA9ON CINEMA / 2026.09.27</p></header><div class="comic-sequence">'
  for i,(heading,copy,bubble,alt) in enumerate(note['panels']):
   body+=f'<section class="comic-panel"><div class="comic-visual">{artwork(note,i,alt[0])}<span class="panel-index" aria-hidden="true">{i+1:02}</span><p class="comic-bubble">{e(bubble[0])}</p></div><div class="comic-caption"><p class="author-aside">{e(note["asides"][i][0])}</p><h2>{e(heading[0])}</h2><p>{e(copy[0])}</p></div></section>'
  body+='</div>'
  if note.get('extra'):body+=f'<aside class="note-character"><p>{e(note["extra"][0])}</p></aside>'
  other=NOTES[1 if season==1 else 0]
  body+=f'<p class="note-disclosure">{e(NOTICE[0])}</p><div class="note-ending"><p>TO BE CONTINUED.</p><a class="button button-white" href="/watch/fall-707-s{season}-ep1/">{LABELS[5][0]} →</a><nav class="note-pagination" aria-label="{LABELS[2][0]}"><a href="/notes/">{LABELS[2][0]}</a><a href="{other["path"]}">{LABELS[4 if season==1 else 3][0]} →</a></nav></div></main>{footer()}</body></html>'
  schema={'@context':'https://schema.org','@type':'Article','headline':title[0],'url':origin+note['path'],'author':{'@type':'Organization','name':'DRA9ON CINEMA'},'image':origin+note['art'],'datePublished':'2026-09-27'}
  folder=out/note['path'].strip('/');folder.mkdir(parents=True,exist_ok=True)
  (folder/'index.html').write_text(head(title[0]+' | DRA9ON CINEMA',intro[0],note['path'],schema)+body,encoding='utf-8')
 schema={'@context':'https://schema.org','@type':'CollectionPage','name':INDEX_TITLE[0],'url':origin+'/notes/'}
 body=f'<body class="watch-page">{header()}<main class="notes-index" id="main">{teaser()}</main>{footer()}</body></html>'
 (out/'notes/index.html').write_text(head(INDEX_TITLE[0]+' | DRA9ON CINEMA',INDEX_INTRO[0],'/notes/',schema)+body,encoding='utf-8')
