const en=document.documentElement.lang==='en',t=(ko,english)=>en?english:ko;
const works=window.PORTFOLIO||[],byId=id=>works.find(v=>v.id===id),$=id=>document.getElementById(id);
const paths={play:'<path d="m8 4 13 8-13 8z" fill="currentColor" stroke="none"/>',plus:'<path d="M12 5v14M5 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||''}</svg>`;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved=new Set();try{const s=JSON.parse(localStorage.getItem('dra9on-portfolio-saved')||'[]');if(Array.isArray(s))saved=new Set(s.filter(id=>byId(id)))}catch{}
let selected=null,category='all',view='all',query='',toastTimer,restoreFocus=null;
function notify(text){if(!$('toast'))return;clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
function syncSaved(){document.querySelectorAll('[data-save]').forEach(b=>{const v=byId(b.dataset.save);if(!v)return;const yes=saved.has(v.id);b.classList.toggle('is-saved',yes);b.setAttribute('aria-pressed',String(yes));b.setAttribute('aria-label',`${v.name} ${yes?t('찜 해제','Remove from list'):t('찜하기','Save')}`);b.innerHTML=icon(yes?'check':'plus')+(b.classList.contains('save-button')?(yes?t('찜한 작품','My list'):t('찜하기','Save')):'')});if(selected&&$('detail-save')){$('detail-save').innerHTML=icon(saved.has(selected.id)?'check':'plus')+(saved.has(selected.id)?t('찜한 작품','My list'):t('찜하기','Save'));$('detail-save').setAttribute('aria-pressed',String(saved.has(selected.id)))}}
function setSaved(id,value){if(!byId(id))throw new Error(t('올바른 작품 ID가 필요합니다.','A valid film ID is required.'));const next=new Set(saved);value?next.add(id):next.delete(id);try{localStorage.setItem('dra9on-portfolio-saved',JSON.stringify([...next]))}catch{notify(t('이 브라우저에서는 찜 목록을 저장할 수 없습니다.','Your list cannot be saved in this browser.'));throw new Error(t('브라우저 저장소 사용 불가','Browser storage is unavailable'))}saved=next;syncSaved();if(category==='saved')render();notify(value?t('찜한 작품에 담았어요','Added to your list'):t('찜한 작품에서 삭제했어요','Removed from your list'))}
function card(v){return `<article class="card"><a class="card-open" href="${v.path}" data-detail="${v.id}" aria-label="${escapeHTML(v.label+' '+v.name)} ${t('상세 보기','View details')}"><div class="card-image"><img src="${v.image}" alt="${escapeHTML(v.name)} ${t('공식 썸네일','official thumbnail')}" width="720" height="405" loading="lazy"><span class="duration">${v.duration||''}</span><span class="card-hover-play"><span>${icon('play')}</span></span></div><p class="card-label">${v.label}</p><h3 class="card-name">${escapeHTML(v.name)}</h3></a><button class="card-save" data-save="${v.id}" aria-label="${escapeHTML(v.name)} ${t('찜하기','Save')}" aria-pressed="false">${icon('plus')}</button></article>`}
function filtered(){return works.filter(v=>(view==='all'||(view==='fall'?!!v.season:v.category==='original'))&&(category==='all'||(category==='saved'?saved.has(v.id):v.category===category))&&(!query||`${v.name} ${v.title} ${v.label} ${v.searchText||''} ${v.season?'FALL 707 낙하707 낙하 707':''}`.toLowerCase().includes(query.toLowerCase())))}
function render(){if(!$('browse-results'))return;const home=category==='all'&&view==='all'&&!query;document.body.classList.toggle('browse-mode',!home);$('hero').hidden=!home;$('home-rows').hidden=!home;$('browse-results').hidden=home;document.querySelectorAll('[data-category]').forEach(b=>{const yes=b.dataset.category===category;b.classList.toggle('active',yes);b.setAttribute('aria-pressed',String(yes))});document.querySelectorAll('[data-view]').forEach(b=>{const yes=b.dataset.view===view;b.classList.toggle('active',yes);yes?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});if(!home){const result=filtered();const labels={all:t('모든 작품','All films'),s1:t('FALL 707 · 시즌 1','FALL 707 · Season 1'),s2:t('FALL 707 · 시즌 2','FALL 707 · Season 2'),full:t('몰아보기','Full movies'),original:t('오리지널 작품','Original films'),saved:t('찜한 작품','My list')};$('browse-title').textContent=query?(en?`Results for “${query}”`:`“${query}” 검색 결과`):category!=='all'?labels[category]:view==='fall'?'FALL 707: REBOOT':view==='original'?t('오리지널 작품','Original films'):t('모든 작품','All films');$('result-count').textContent=`${result.length}${t('편',result.length===1?' film':' films')}${category==='saved'?t(' · 이 브라우저에 저장된 목록',' · Saved in this browser'):''}`;$('results-grid').innerHTML=result.map(card).join('');$('empty-state').hidden=result.length>0}syncSaved();document.querySelectorAll('.shelf-track').forEach(updateArrows)}
function updateArrows(track){const prev=document.querySelector(`[data-scroll="${track.id}"][data-direction="-1"]`),next=document.querySelector(`[data-scroll="${track.id}"][data-direction="1"]`);if(prev)prev.disabled=track.scrollLeft<=2;if(next)next.disabled=track.scrollLeft+track.clientWidth>=track.scrollWidth-3}
function showDetail(id){const v=byId(id);if(!v||!$('detail-dialog'))return;restoreFocus=document.activeElement;selected=v;$('detail-title').textContent=v.name;$('detail-label').textContent=v.label;$('detail-image').src=v.image;$('detail-image').alt=v.name+t(' 공식 썸네일',' official thumbnail');$('detail-description').textContent=v.summary;$('detail-meta').textContent=`DRA9ON CINEMA · ${v.duration||''}`;$('detail-page').href=v.path;syncSaved();$('detail-dialog').showModal()}
function createPlayer(id){const v=byId(id);if(!v)throw new Error(t('알 수 없는 영상입니다.','Unknown film.'));const frame=document.createElement('iframe');frame.src=`https://www.youtube-nocookie.com/embed/${v.id}?rel=0&playsinline=1&autoplay=0&hl=${en?'en':'ko'}${en?'&cc_lang_pref=en':''}`;frame.title=v.title;frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;return frame}
function nextVideo(v){let seq=works.filter(w=>w.category===v.category);if(['s1','s2'].includes(v.category))seq.sort((a,b)=>a.episode-b.episode);return seq[seq.findIndex(w=>w.id===v.id)+1]||(v.category==='s1'?works.find(w=>w.category==='s2'&&w.episode===1):null)}
function play(id){const v=byId(id);if(!v)return;if(!$('player-dialog')){location.href=v.path;return}if($('detail-dialog').open)$('detail-dialog').close();restoreFocus=document.activeElement;$('player-title').textContent=`${v.label} · ${v.name}`;$('player-youtube').href=`https://www.youtube.com/watch?v=${v.id}`;const next=nextVideo(v);$('player-next').hidden=!next;if(next)$('player-next').href=next.path;$('player-mount').replaceChildren(createPlayer(id));$('player-dialog').showModal()}
async function share(id){const v=byId(id);if(!v)return;const url=new URL(v.path,location.origin).href;try{await navigator.clipboard.writeText(url);notify(t('작품 링크를 복사했어요','Film link copied'))}catch{notify(t('링크 복사가 제한되어 작품 페이지를 엽니다.','Copy unavailable. Opening the film page.'));location.href=v.path}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-detail]');if(a&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&e.button===0&&$('detail-dialog')){e.preventDefault();showDetail(a.dataset.detail);return}const b=e.target.closest('button');if(!b)return;if(b.dataset.play)play(b.dataset.play);if(b.dataset.save){try{setSaved(b.dataset.save,!saved.has(b.dataset.save))}catch{}}if(b.dataset.share)share(b.dataset.share);if(b.dataset.view){view=b.dataset.view;category='all';query='';$('search').value='';render();window.scrollTo({top:0,behavior:'instant'})}if(b.dataset.category){category=b.dataset.category;view='all';render()}if(b.dataset.scroll){const t=$(b.dataset.scroll);t.scrollBy({left:Number(b.dataset.direction)*t.clientWidth*.85,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})}});
if($('search-toggle')){$('search-toggle').addEventListener('click',()=>{const opening=$('search').hidden;$('search').hidden=!opening;$('search-wrap').classList.toggle('expanded',opening);$('search-toggle').setAttribute('aria-expanded',String(opening));if(opening)$('search').focus();else{query='';$('search').value='';render()}});$('search').addEventListener('input',e=>{query=e.target.value.trim().slice(0,100);render()});$('search').addEventListener('keydown',e=>{if(e.key==='Escape'){$('search-toggle').click();$('search-toggle').focus()}})}
if($('reset-browse'))$('reset-browse').addEventListener('click',()=>{view='all';category='all';query='';$('search').value='';render();window.scrollTo({top:0,behavior:'instant'})});
if($('detail-dialog')){$('detail-close').addEventListener('click',()=>$('detail-dialog').close());$('detail-play').addEventListener('click',()=>play(selected.id));$('detail-save').addEventListener('click',()=>{try{setSaved(selected.id,!saved.has(selected.id))}catch{}});$('detail-share').addEventListener('click',()=>share(selected.id));$('player-close').addEventListener('click',()=>$('player-dialog').close());$('player-dialog').addEventListener('close',()=>{$('player-mount').replaceChildren();if(restoreFocus?.isConnected)restoreFocus.focus()});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}))}
document.querySelectorAll('.shelf-track').forEach(t=>{t.addEventListener('scroll',()=>updateArrows(t),{passive:true});updateArrows(t)});window.addEventListener('resize',()=>document.querySelectorAll('.shelf-track').forEach(updateArrows));syncSaved();
if(document.modelContext?.registerTool&&$('browse-results')){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'browse_portfolio',title:t('포트폴리오 검색','Search portfolio'),description:t('검색어로 DRA9ON CINEMA의 작품을 찾아 화면에 표시합니다.','Find and display DRA9ON CINEMA films by search term.'),inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.query!=='string'||input.query.length>100||Object.keys(input).some(k=>k!=='query'))throw new Error(t('100자 이하의 검색어를 입력해 주세요.','Enter a search term of up to 100 characters.'));view='all';category='all';query=input.query.trim();$('search').value=query;render();return {works:filtered().map(v=>({id:v.id,title:v.name,url:v.path}))}}});register({name:'set_saved_work',title:t('작품 찜하기','Save film'),description:t('이 브라우저의 찜 목록에 작품을 저장하거나 제거합니다.','Add or remove a film from the list saved in this browser.'),inputSchema:{type:'object',properties:{id:{type:'string'},saved:{type:'boolean'}},required:['id','saved'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.id!=='string'||!byId(input.id)||typeof input.saved!=='boolean'||Object.keys(input).some(k=>!['id','saved'].includes(k)))throw new Error(t('올바른 작품 ID와 저장 여부를 입력해 주세요.','Enter a valid film ID and saved state.'));setSaved(input.id,input.saved);return {id:input.id,saved:saved.has(input.id)}}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}

// Carry the current section when switching between the static language routes.
document.querySelectorAll('[data-language]').forEach(a=>{a.addEventListener('click',()=>{const url=new URL(a.href);url.hash=location.hash;a.href=url.href})});
